name: dvmvs_env
channels:
  - pytorch
  - fvcore
  - pytorch3d
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.5.1
  - torchvision=0.6.1
  - cudatoolkit=10.2
  - opencv=4.4.0
  - tqdm=4.50.2
  - scipy=1.5.2
  - fvcore=0.1.2
  - pytorch3d=0.2.5
  - pip
  # - pip:
  #   - pytools==2020.4
  #   - kornia==0.3.2
  #   - path==15.0.0
  #   - protobuf==3.13.0
  #   - tensorboardx==2.1
  #   - pandaset-sdk